[ -z "$PS1" ] && return # If not running interactively, don't do anything
[ -f /etc/bashrc ] && /etc/bashrc #Source global bashrc if required

# set the XDG Base Directory Locations, load compliance hacks
    export XDG_CONFIG_HOME=$HOME/.local/etc
    export XDG_DATA_HOME=$HOME/.local/share
    export XDG_CACHE_HOME=$HOME/.local/tmp
    [ -f $XDG_CONFIG_HOME/bash/xdg.sh ] && . $XDG_CONFIG_HOME/bash/xdg.sh

# Preferred Prompt Setting
    export PS1="\u@\h:\w\\$ "

# enable programmable completion features
    [ -f /etc/bash_completion ] && ! shopt -oq posix && . /etc/bash_completion

# Set Shell options to increase functionality
    shopt -s autocd               # Enable changing directory without cd
    shopt -s cdspell              # Spelling correction for cd
    shopt -s checkwinsize         # Adjust text to window size after commands
    shopt -s dirspell             # Spelling correction for dirs
    shopt -s dotglob              # Enable globbing for dotfiles
    shopt -s extglob              # Extended globbing
    shopt -s histappend           # Append to history, don't overwrite
    shopt -s histreedit           # Re-edit failed history substitutions
    shopt -s nocaseglob           # Ignore cases for globbing filenames
    export HISTCONTROL=ignoreboth # Ignore duplicate/blank lines in history
    export HISTSIZE=10000         # 10K command in history
    export LC_COLLATE="C"         # Change sorting to list dotfiles first
    export EDITOR='/usr/bin/vim'  # Use vim for light edits
    export VISUAL='/usr/bin/vim'  # Use vim for heavy edits

# Get rid of the terminal suspend/resume bindings
stty stop undef
stty start undef

# Colour the terminal
    [ -x /usr/bin/dircolors ] && eval "$(dircolors -b)"
    export LESS=-R
    export LESS_TERMCAP_mb=$(printf "\e[1;31m")
    export LESS_TERMCAP_md=$(printf "\e[1;31m")
    export LESS_TERMCAP_me=$(printf "\e[0m")
    export LESS_TERMCAP_se=$(printf "\e[0m")
    export LESS_TERMCAP_so=$(printf "\e[1;44;33m")
    export LESS_TERMCAP_ue=$(printf "\e[0m")
    export LESS_TERMCAP_us=$(printf "\e[1;32m")

# Load Aliases and Functions
    [ -f "$XDG_CONFIG_HOME"/bash/aliases.sh ] && .  $XDG_CONFIG_HOME/bash/aliases.sh
    [ -f "$XDG_CONFIG_HOME"/bash/saliases.sh ] && .  $XDG_CONFIG_HOME/bash/saliases.sh
    [ -d $XDG_CONFIG_HOME/bash/functions/ ] &&
        for f in $XDG_CONFIG_HOME/bash/functions/*; do . $f; done

# Append Additional Executables to $PATH
    [[ :$PATH: != *:"$HOME/.local/bin":* ]] && PATH="$HOME/.local/bin:${PATH}"

# Ensure GPG Agent is running if it can
[ -z $GPG_AGENT_INFO ] && command_exists gpg-agent &&
    eval $(gpg-agent --daemon --write-env-file="$GNUPGHOME/gpg-agent-info" 2>/dev/null)
