#Source global bashrc if required
    [ -f /etc/bashrc ] && . /etc/bashrc

# enable programmable completion features
    [ -f /etc/bash_completion ] && ! shopt -oq posix && . /etc/bash_completion

# Set Shell options to increase functionality
    shopt -s autocd               # Enable changing directory without cd
    shopt -s cdspell              # Spelling correction for cd
    shopt -s checkwinsize         # Adjust text to window size after commands
    shopt -s dirspell             # Spelling correction for dirs
    shopt -s dotglob              # Enable globbing for dotfiles
    shopt -s extglob              # Extended globbing
    shopt -s globstar             # ZSH-like ** globbing (recursive dir match)
    shopt -s histappend           # Append to history, don't overwrite
    shopt -s histreedit           # Re-edit failed history substitutions
    shopt -s nocaseglob           # Ignore cases for globbing filenames

# Source common shell config
    XDG_CONFIG_HOME="$(dirname ${BASH_SOURCE[0]})/.."
    source "$XDG_CONFIG_HOME/sh/xdg.sh"
    source "$XDG_CONFIG_HOME/sh/rc.sh"

# preferred prompt setting (jobcount in blue if >0), user@host:path if nonlocal
    export PS1=' $([ \j -gt 0 ] && echo \[$col_bblue\]\j\[$col_reset\]\ )$(prmpt)'
