[ -z "$PS1" ] && return # If not running interactively, don't do anything
[ -f /etc/bashrc ] && . /etc/bashrc #Source global bashrc if required

# set the XDG Base Directory Locations, load compliance hacks
    export XDG_CONFIG_HOME=$HOME/.config
    export XDG_DATA_HOME=$HOME/.local/share
    export XDG_BIN_HOME=$HOME/.local/bin
    export XDG_LIB_HOME=$HOME/.local/lib
    export XDG_CACHE_HOME=$HOME/.cache
    [ -f $XDG_CONFIG_HOME/bash/xdg.sh ] && . $XDG_CONFIG_HOME/bash/xdg.sh

# enable programmable completion features
    [ -f /etc/bash_completion ] && ! shopt -oq posix && . /etc/bash_completion

# Set Shell options to increase functionality
    shopt -s autocd               # Enable changing directory without cd
    shopt -s cdspell              # Spelling correction for cd
    shopt -s checkwinsize         # Adjust text to window size after commands
    shopt -s dirspell             # Spelling correction for dirs
    shopt -s dotglob              # Enable globbing for dotfiles
    shopt -s extglob              # Extended globbing
    shopt -s globstar             # ZSH-like ** globbing (recursive dir match)
    shopt -s histappend           # Append to history, don't overwrite
    shopt -s histreedit           # Re-edit failed history substitutions
    shopt -s nocaseglob           # Ignore cases for globbing filenames
    export HISTCONTROL=ignoreboth # Ignore duplicate/blank lines in history
    export HISTSIZE=100000        # 100K command in history
    export LC_COLLATE="C"         # Change sorting to list dotfiles first
    export EDITOR='vim'           # Use vim for light edits
    export VISUAL='vim'           # Use vim for heavy edits

# Get rid of the terminal suspend/resume bindings
    stty stop undef
    stty start undef

# Colour the terminal
    [ -x /usr/bin/dircolors ] && eval "$(dircolors -b $XDG_CONFIG_HOME/bash/dircolors)"
    export LESS=-R
    export LESS_TERMCAP_mb=$(printf "\e[1;31m")
    export LESS_TERMCAP_md=$(printf "\e[1;31m")
    export LESS_TERMCAP_me=$(printf "\e[0m")
    export LESS_TERMCAP_se=$(printf "\e[0m")
    export LESS_TERMCAP_so=$(printf "\e[1;44;33m")
    export LESS_TERMCAP_ue=$(printf "\e[0m")
    export LESS_TERMCAP_us=$(printf "\e[1;32m")

# Load Aliases and Functions
    [ -d $XDG_CONFIG_HOME/bash/functions/ ] &&
        for f in $XDG_CONFIG_HOME/bash/functions/*; do . $f; done
    [ -f "$XDG_CONFIG_HOME"/bash/aliases.sh ] && .  $XDG_CONFIG_HOME/bash/aliases.sh
    [ -f "$XDG_CONFIG_HOME"/bash/saliases.sh ] && .  $XDG_CONFIG_HOME/bash/saliases.sh
    clean_home

# preferred prompt setting (jobcount in blue if >0), user@host:path if nonlocal
    export PS1=' $([ \j -gt 0 ] && echo \[$col_bblue\]\j\[$col_reset\]\ )$(prmpt)'

# Append Additional Executables to $PATH
    [ -d /usr/local/opt/coreutils ] &&
        export PATH="/usr/local/opt/coreutils/libexec/gnubin:${PATH}" &&
        export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
    export PATH="$HOME/.local/bin:${PATH}"
    export NODE_PATH="$HOME/.local/lib/node_modules"

# Ensure GPG Agent is running if it can
[ -z $GPG_AGENT_INFO ] && command_exists gpg-agent &&
    eval $(gpg-agent --daemon --enable-ssh-support --write-env-file="$GNUPGHOME/gpg-agent-info" 2>/dev/null) &&
    export SSH_AUTH_SOCK

# Start X if we're at seat1 and it's not there, else open tmux
if [[ -z $DISPLAY && $XDG_VTNR -eq 1 ]]; then
	exec startx $XDG_CONFIG_HOME/X11/xinitrc
else
	tmx default
fi
